import type { Archetype, ArchetypeKey } from "./types.js";

export const ARCHETYPES: Archetype[] = [
  {
    key: "explorer",
    id: "01",
    name: "AI探險家",
    title: "未知開路者",
    shortDescription: "你往沒有地圖的地方去，因為那裡才有風景。",
    manifesto: "你總是第一個走進未知的人。",
    coreDesire: "探索新的可能，保持自由與好奇。",
    coreFear: "被固定規則困住，失去嘗試未知的空間。",
    superPower: "快速進入新領域，替團隊找到第一條路。",
    shadow: "容易追逐新鮮感，還沒累積成果就轉向下一個刺激。",
    growthPath: "把探索轉成可複製的路線，讓冒險留下成果。",
    bestPartner: "AI建造者",
    symbol: "◇",
    colorHue: 288,
    element: "風",
    animal: "隼",
    dimensionProfile: {
      explore: 95,
      action: 82,
      risk: 76,
      create: 68,
      influence: 46,
      build: 38,
    },
    imagePaths: {
      portrait: "/assets/archetypes/explorer.png",
      shareCard: "/assets/share-cards/explorer.png",
      placeholder: "/assets/placeholders/explorer.png",
    },
  },
  {
    key: "craftsman",
    id: "02",
    name: "AI工匠",
    title: "工具鍛造者",
    shortDescription: "你相信真正的價值，來自反覆打磨。",
    manifesto: "你把工具磨成自己的武器。",
    coreDesire: "把能力、工具與作品磨到可靠又精準。",
    coreFear: "被粗糙的速度取代，失去手感與專業深度。",
    superPower: "把模糊需求打磨成穩定可用的成果。",
    shadow: "可能過度追求完美，錯過快速驗證的時機。",
    growthPath: "讓作品先上場，再用真實回饋繼續打磨。",
    bestPartner: "AI探險家",
    symbol: "◆",
    colorHue: 255,
    element: "金",
    animal: "獾",
    dimensionProfile: {
      explore: 42,
      action: 58,
      risk: 28,
      create: 54,
      influence: 32,
      build: 86,
    },
    imagePaths: {
      portrait: "/assets/archetypes/craftsman.png",
      shareCard: "/assets/share-cards/craftsman.png",
      placeholder: "/assets/placeholders/craftsman.png",
    },
  },
  {
    key: "guardian",
    id: "03",
    name: "AI守護者",
    title: "信任守門人",
    shortDescription: "你不是抗拒未來，而是不想讓重要的人被浪潮丟下。",
    manifesto: "你在變動裡守住重要的人。",
    coreDesire: "在變動中守住安全、信任與人的位置。",
    coreFear: "技術推進太快，讓脆弱的人被迫承擔代價。",
    superPower: "看見風險與人心，替團隊建立安全邊界。",
    shadow: "可能因擔心風險而放慢必要的改變。",
    growthPath: "把保護轉成清楚規則，讓大家安心前進。",
    bestPartner: "AI發明家",
    symbol: "●",
    colorHue: 210,
    element: "水",
    animal: "鯨",
    dimensionProfile: {
      explore: 36,
      action: 56,
      risk: 24,
      create: 42,
      influence: 55,
      build: 62,
    },
    imagePaths: {
      portrait: "/assets/archetypes/guardian.png",
      shareCard: "/assets/share-cards/guardian.png",
      placeholder: "/assets/placeholders/guardian.png",
    },
  },
  {
    key: "navigator",
    id: "04",
    name: "AI領航員",
    title: "迷霧領路人",
    shortDescription: "你看到方向，也願意帶人一起前進。",
    manifesto: "你能帶大家穿過迷霧。",
    coreDesire: "在混亂中找到方向，帶大家抵達下一站。",
    coreFear: "群體失去方向，各自被浪潮推散。",
    superPower: "整合資訊、凝聚人心、把未知變成路線。",
    shadow: "可能承擔太多責任，忘了讓他人一起掌舵。",
    growthPath: "把方向感變成共同地圖，而不是個人負重。",
    bestPartner: "AI策士",
    symbol: "▲",
    colorHue: 170,
    element: "星",
    animal: "海豚",
    dimensionProfile: {
      explore: 72,
      action: 78,
      risk: 55,
      create: 56,
      influence: 88,
      build: 66,
    },
    imagePaths: {
      portrait: "/assets/archetypes/navigator.png",
      shareCard: "/assets/share-cards/navigator.png",
      placeholder: "/assets/placeholders/navigator.png",
    },
  },
  {
    key: "strategist",
    id: "05",
    name: "AI策士",
    title: "局勢解碼者",
    shortDescription: "你不急著行動，你先判斷勢能。",
    manifesto: "你總是先看見局勢背後的規則。",
    coreDesire: "理解規則、看見局勢，做出高勝率選擇。",
    coreFear: "在資訊不足時被迫表態，做出錯誤判斷。",
    superPower: "拆解複雜局面，找出關鍵槓桿。",
    shadow: "可能分析過久，讓機會在等待中流失。",
    growthPath: "替策略設定行動期限，把洞察轉成實驗。",
    bestPartner: "AI交易員",
    symbol: "◎",
    colorHue: 135,
    element: "木",
    animal: "狐",
    dimensionProfile: {
      explore: 58,
      action: 42,
      risk: 50,
      create: 52,
      influence: 68,
      build: 70,
    },
    imagePaths: {
      portrait: "/assets/archetypes/strategist.png",
      shareCard: "/assets/share-cards/strategist.png",
      placeholder: "/assets/placeholders/strategist.png",
    },
  },
  {
    key: "inventor",
    id: "06",
    name: "AI發明家",
    title: "未來造物者",
    shortDescription: "你不是使用未來，你會創造未來。",
    manifesto: "你讓不存在的東西開始存在。",
    coreDesire: "把腦中的新東西做出來，證明另一種可能。",
    coreFear: "只能使用別人的系統，無法創造自己的答案。",
    superPower: "快速組合技術、概念與想像，做出原型。",
    shadow: "可能愛上點子，忽略落地與維護。",
    growthPath: "替創造力加上節奏，讓發明能被使用。",
    bestPartner: "AI守護者",
    symbol: "✦",
    colorHue: 95,
    element: "雷",
    animal: "蜂鳥",
    dimensionProfile: {
      explore: 86,
      action: 60,
      risk: 72,
      create: 96,
      influence: 52,
      build: 58,
    },
    imagePaths: {
      portrait: "/assets/archetypes/inventor.png",
      shareCard: "/assets/share-cards/inventor.png",
      placeholder: "/assets/placeholders/inventor.png",
    },
  },
  {
    key: "trader",
    id: "07",
    name: "AI交易員",
    title: "機會捕手",
    shortDescription: "你看見別人忽略的價差與時機。",
    manifesto: "你在不確定裡聞到機會。",
    coreDesire: "在變動中抓住機會，讓判斷快速變成回報。",
    coreFear: "錯過關鍵時機，眼睜睜看機會流走。",
    superPower: "敏銳感知市場、資源與時機的錯位。",
    shadow: "可能太快出手，低估長期風險。",
    growthPath: "替每次出手設定停損與復盤，讓直覺變準。",
    bestPartner: "AI策士",
    symbol: "◈",
    colorHue: 55,
    element: "火",
    animal: "獵豹",
    dimensionProfile: {
      explore: 70,
      action: 84,
      risk: 90,
      create: 54,
      influence: 50,
      build: 40,
    },
    imagePaths: {
      portrait: "/assets/archetypes/trader.png",
      shareCard: "/assets/share-cards/trader.png",
      placeholder: "/assets/placeholders/trader.png",
    },
  },
  {
    key: "mentor",
    id: "08",
    name: "AI導師",
    title: "能力傳遞者",
    shortDescription: "你真正的能力，是把理解傳給別人。",
    manifesto: "你讓身邊的人也一起變強。",
    coreDesire: "讓身邊的人理解、成長，跟上新的時代。",
    coreFear: "知識只停在自己身上，無法真正改變他人。",
    superPower: "把複雜事物講清楚，讓人敢開始行動。",
    shadow: "可能照顧太多人，忽略自己的進化。",
    growthPath: "建立教學系統，讓影響力不只靠你本人。",
    bestPartner: "AI領航員",
    symbol: "◉",
    colorHue: 28,
    element: "光",
    animal: "貓頭鷹",
    dimensionProfile: {
      explore: 56,
      action: 58,
      risk: 36,
      create: 55,
      influence: 90,
      build: 62,
    },
    imagePaths: {
      portrait: "/assets/archetypes/mentor.png",
      shareCard: "/assets/share-cards/mentor.png",
      placeholder: "/assets/placeholders/mentor.png",
    },
  },
  {
    key: "builder",
    id: "09",
    name: "AI建造者",
    title: "系統築城者",
    shortDescription: "你不只完成一件事，你會留下結構。",
    manifesto: "你打造能留下來的系統。",
    coreDesire: "打造能長期運作、能被別人接續的系統。",
    coreFear: "成果只是一次性煙火，無法累積成真正資產。",
    superPower: "把混亂整理成流程、工具與可持續架構。",
    shadow: "可能太重視穩定，延遲必要的突破。",
    growthPath: "替系統保留實驗空間，讓穩定與創新共存。",
    bestPartner: "AI探險家",
    symbol: "▣",
    colorHue: 332,
    element: "土",
    animal: "象",
    dimensionProfile: {
      explore: 44,
      action: 70,
      risk: 38,
      create: 58,
      influence: 56,
      build: 96,
    },
    imagePaths: {
      portrait: "/assets/archetypes/builder.png",
      shareCard: "/assets/share-cards/builder.png",
      placeholder: "/assets/placeholders/builder.png",
    },
  },
] as const satisfies Archetype[];

export const ARCHETYPE_KEYS = ARCHETYPES.map((item) => item.key);

export const ARCHETYPE_BY_KEY = Object.fromEntries(
  ARCHETYPES.map((item) => [item.key, item]),
) as Record<ArchetypeKey, Archetype>;
