import type { ArchetypeKey, DimensionEffect, QuizOption, QuizScenario } from "./types.js";

export type OptionBibleEntry = {
  sceneId: string;
  optionId: "a" | "b" | "c";
  optionText: string;
  emotion: string;
  value: string;
  dimensionEffect: DimensionEffect;
  primaryArchetype: ArchetypeKey;
  secondaryArchetype: ArchetypeKey;
  visualMood: string[];
  visualSymbol: string[];
  imagePath: string;
};

export const OPTION_BIBLE: OptionBibleEntry[] = [
  {
    sceneId: "scene-01-message",
    optionId: "a",
    optionText: "我想再加新點子。",
    emotion: "加點子",
    value: "可能性",
    dimensionEffect: { explore: 3, create: 2, risk: 1, action: 1 },
    primaryArchetype: "explorer",
    secondaryArchetype: "inventor",
    visualMood: ["希望", "興奮", "未知召喚"],
    visualSymbol: ["光", "星圖", "羅盤"],
    imagePath: "assets/scenes/options/scene-01-a.png",
  },
  {
    sceneId: "scene-01-message",
    optionId: "b",
    optionText: "我先檢查細節。",
    emotion: "檢查",
    value: "品質",
    dimensionEffect: { build: 3, action: 2, create: 1, risk: -1 },
    primaryArchetype: "craftsman",
    secondaryArchetype: "builder",
    visualMood: ["專注", "精準", "手感"],
    visualSymbol: ["工具", "鍛造光", "刻線"],
    imagePath: "assets/scenes/options/scene-01-b.png",
  },
  {
    sceneId: "scene-01-message",
    optionId: "c",
    optionText: "我先想誰會受影響。",
    emotion: "關心",
    value: "人",
    dimensionEffect: { influence: 3, build: 1, risk: -1, explore: 1 },
    primaryArchetype: "guardian",
    secondaryArchetype: "mentor",
    visualMood: ["關照", "警覺", "溫暖"],
    visualSymbol: ["守護圈", "人群光點", "盾"],
    imagePath: "assets/scenes/options/scene-01-c.png",
  },
  {
    sceneId: "scene-02-system-change",
    optionId: "a",
    optionText: "我帶大家先試用。",
    emotion: "帶頭",
    value: "方向",
    dimensionEffect: { influence: 3, action: 2, explore: 2, build: 1 },
    primaryArchetype: "navigator",
    secondaryArchetype: "mentor",
    visualMood: ["清醒", "堅定", "領路"],
    visualSymbol: ["北極星", "路線", "光橋"],
    imagePath: "assets/scenes/options/scene-02-a.png",
  },
  {
    sceneId: "scene-02-system-change",
    optionId: "b",
    optionText: "我先弄懂規則。",
    emotion: "理解",
    value: "判斷",
    dimensionEffect: { build: 2, influence: 1, create: 1, action: -1, risk: -1 },
    primaryArchetype: "strategist",
    secondaryArchetype: "builder",
    visualMood: ["冷靜", "洞察", "結構"],
    visualSymbol: ["棋盤", "資料網格", "眼"],
    imagePath: "assets/scenes/options/scene-02-b.png",
  },
  {
    sceneId: "scene-02-system-change",
    optionId: "c",
    optionText: "我做一份操作流程。",
    emotion: "整理",
    value: "可用",
    dimensionEffect: { action: 3, build: 3, create: 1, risk: 1 },
    primaryArchetype: "craftsman",
    secondaryArchetype: "builder",
    visualMood: ["務實", "穩定", "可交付"],
    visualSymbol: ["流程線", "工作台", "模組"],
    imagePath: "assets/scenes/options/scene-02-c.png",
  },
  {
    sceneId: "scene-03-risk-opportunity",
    optionId: "a",
    optionText: "先小試一把。",
    emotion: "試試看",
    value: "時機",
    dimensionEffect: { risk: 3, action: 3, explore: 2, build: -1 },
    primaryArchetype: "trader",
    secondaryArchetype: "explorer",
    visualMood: ["速度", "刺激", "機會"],
    visualSymbol: ["閃電", "價差光環", "跳躍線"],
    imagePath: "assets/scenes/options/scene-03-a.png",
  },
  {
    sceneId: "scene-03-risk-opportunity",
    optionId: "b",
    optionText: "先算成本風險。",
    emotion: "先評估",
    value: "勝率",
    dimensionEffect: { build: 2, influence: 1, risk: -1, action: -1, explore: 1 },
    primaryArchetype: "strategist",
    secondaryArchetype: "guardian",
    visualMood: ["冷靜", "精算", "等待"],
    visualSymbol: ["天秤", "棋子", "矩陣"],
    imagePath: "assets/scenes/options/scene-03-b.png",
  },
  {
    sceneId: "scene-03-risk-opportunity",
    optionId: "c",
    optionText: "改成小實驗。",
    emotion: "小實驗",
    value: "創新",
    dimensionEffect: { create: 3, explore: 2, risk: 2, action: 1 },
    primaryArchetype: "inventor",
    secondaryArchetype: "explorer",
    visualMood: ["煉成", "實驗", "突破"],
    visualSymbol: ["火花", "實驗陣", "變形核心"],
    imagePath: "assets/scenes/options/scene-03-c.png",
  },
  {
    sceneId: "scene-04-friend-anxiety",
    optionId: "a",
    optionText: "我教他用 AI 做事。",
    emotion: "教方法",
    value: "賦能",
    dimensionEffect: { influence: 3, create: 1, build: 1, action: 1 },
    primaryArchetype: "mentor",
    secondaryArchetype: "navigator",
    visualMood: ["溫暖", "理解", "傳火"],
    visualSymbol: ["書", "火光", "雙人光點"],
    imagePath: "assets/scenes/options/scene-04-a.png",
  },
  {
    sceneId: "scene-04-friend-anxiety",
    optionId: "b",
    optionText: "我先陪他穩住。",
    emotion: "陪一下",
    value: "安全",
    dimensionEffect: { influence: 2, build: 2, risk: -2, action: 1 },
    primaryArchetype: "guardian",
    secondaryArchetype: "mentor",
    visualMood: ["安定", "陪伴", "信任"],
    visualSymbol: ["盾", "暖光", "安全結界"],
    imagePath: "assets/scenes/options/scene-04-b.png",
  },
  {
    sceneId: "scene-04-friend-anxiety",
    optionId: "c",
    optionText: "我幫他排下一步。",
    emotion: "排路線",
    value: "導航",
    dimensionEffect: { influence: 2, build: 2, explore: 2, action: 1 },
    primaryArchetype: "navigator",
    secondaryArchetype: "strategist",
    visualMood: ["清楚", "前進", "陪走"],
    visualSymbol: ["路線圖", "星標", "分岔路"],
    imagePath: "assets/scenes/options/scene-04-c.png",
  },
  {
    sceneId: "scene-05-blank-canvas",
    optionId: "a",
    optionText: "做一個新點子。",
    emotion: "新點子",
    value: "原創",
    dimensionEffect: { create: 3, explore: 3, risk: 2, action: 1 },
    primaryArchetype: "inventor",
    secondaryArchetype: "explorer",
    visualMood: ["誕生", "靈感", "未來"],
    visualSymbol: ["光門", "種子核心", "空白畫布"],
    imagePath: "assets/scenes/options/scene-05-a.png",
  },
  {
    sceneId: "scene-05-blank-canvas",
    optionId: "b",
    optionText: "先搭基本流程。",
    emotion: "搭流程",
    value: "累積",
    dimensionEffect: { build: 3, action: 2, create: 1, risk: -1 },
    primaryArchetype: "builder",
    secondaryArchetype: "craftsman",
    visualMood: ["穩固", "秩序", "長期"],
    visualSymbol: ["結構塔", "地基", "模組網格"],
    imagePath: "assets/scenes/options/scene-05-b.png",
  },
  {
    sceneId: "scene-05-blank-canvas",
    optionId: "c",
    optionText: "先找誰真的需要。",
    emotion: "找需求",
    value: "流動",
    dimensionEffect: { risk: 2, action: 2, explore: 2, influence: 1 },
    primaryArchetype: "trader",
    secondaryArchetype: "strategist",
    visualMood: ["敏銳", "交換", "流通"],
    visualSymbol: ["水流", "節點交換", "機會盤"],
    imagePath: "assets/scenes/options/scene-05-c.png",
  },
  {
    sceneId: "scene-06-future-self",
    optionId: "a",
    optionText: "我有勇敢開始。",
    emotion: "開始",
    value: "未知",
    dimensionEffect: { explore: 3, action: 2, risk: 2, create: 1 },
    primaryArchetype: "explorer",
    secondaryArchetype: "trader",
    visualMood: ["召喚", "回望", "勇氣"],
    visualSymbol: ["遠方門", "星路", "狼影"],
    imagePath: "assets/scenes/options/scene-06-a.png",
  },
  {
    sceneId: "scene-06-future-self",
    optionId: "b",
    optionText: "我留下可用系統。",
    emotion: "留下",
    value: "系統",
    dimensionEffect: { build: 3, action: 2, influence: 1, risk: -1 },
    primaryArchetype: "builder",
    secondaryArchetype: "guardian",
    visualMood: ["承載", "穩定", "長久"],
    visualSymbol: ["城牆", "資料庫", "根系"],
    imagePath: "assets/scenes/options/scene-06-b.png",
  },
  {
    sceneId: "scene-06-future-self",
    optionId: "c",
    optionText: "我幫到更多人。",
    emotion: "幫人",
    value: "影響",
    dimensionEffect: { influence: 3, build: 2, create: 1, action: 1 },
    primaryArchetype: "mentor",
    secondaryArchetype: "navigator",
    visualMood: ["傳承", "共學", "光源"],
    visualSymbol: ["開卷", "火炬", "群星"],
    imagePath: "assets/scenes/options/scene-06-c.png",
  },
];

export function findOptionBibleEntry(sceneId: string, optionId: "a" | "b" | "c"): OptionBibleEntry | undefined {
  return OPTION_BIBLE.find((entry) => entry.sceneId === sceneId && entry.optionId === optionId);
}

export function createQuizScenariosFromOptionBible(): QuizScenario[] {
  const metadata: Record<string, Omit<QuizScenario, "options">> = {
    "scene-01-message": {
      id: "scene-01-message",
      chapter: "一",
      chTitle: "工作被完成",
      line: "AI 已把報告寫好了。",
    },
    "scene-02-system-change": {
      id: "scene-02-system-change",
      chapter: "二",
      chTitle: "公司導入AI",
      line: "公司突然換成 AI 系統。",
    },
    "scene-03-risk-opportunity": {
      id: "scene-03-risk-opportunity",
      chapter: "三",
      chTitle: "新專案邀約",
      line: "有人邀你做 AI 新專案。",
    },
    "scene-04-friend-anxiety": {
      id: "scene-04-friend-anxiety",
      chapter: "四",
      chTitle: "好友求救",
      line: "好友問：我會被AI取代嗎？",
    },
    "scene-05-blank-canvas": {
      id: "scene-05-blank-canvas",
      chapter: "五",
      chTitle: "新案開始",
      line: "你拿到一個全新專案。",
    },
    "scene-06-future-self": {
      id: "scene-06-future-self",
      chapter: "六",
      chTitle: "一年後回看",
      line: "一年後回看今天，你希望？",
    },
  };

  return Object.values(metadata).map((scenario) => ({
    ...scenario,
    options: OPTION_BIBLE.filter((entry) => entry.sceneId === scenario.id).map<QuizOption>((entry) => ({
      id: entry.optionId,
      mood: entry.emotion,
      title: entry.optionText,
      archetypeKey: entry.primaryArchetype,
      secondaryArchetype: entry.secondaryArchetype,
      dimensionEffect: entry.dimensionEffect,
      imagePath: entry.imagePath,
    })),
  }));
}
